apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-ausf
  namespace: free5gc
  labels:
    epc-mode: ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: ausf
  template:
    metadata:
      labels:
        epc-mode: ausf
        app: free5gc-ausf
    spec:
      nodeSelector:
        nodetype: server
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: whitesnake
      containers:
        - name: ausf
          image: free5gc/ausf:latest
          imagePullPolicy: Always
          command: ["./ausf", "-c", "/free5gc/config/ausfConfig.yaml"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: /free5gc/config
      volumes:
        - name: config-volume
          configMap:
            name: ausf-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf-config
  namespace: free5gc
data:
  ausfConfig.yaml: |
    info:
      version: 1.0.3
      description: AUSF initial local configuration

    configuration:
      sbi:
        scheme: http
        registerIPv4: ausf.free5gc.svc.cluster.local
        bindingIPv4: 0.0.0.0
        port: 8000
        tls:
          pem: cert/ausf.pem
          key: cert/ausf.key
      serviceNameList:
        - nausf-auth
      nrfUri: http://nrf.free5gc.svc.cluster.local:8000
      plmnSupportList:
        - mcc: 208
          mnc: 93
        - mcc: 123
          mnc: 45
      groupId: ausfGroup001
      eapAkaSupiImsiPrefix: false

    logger:
      enable: true
      level: info
      reportCaller: false
---
apiVersion: v1
kind: Service
metadata:
  name: ausf
  namespace: free5gc
spec:
  selector:
    epc-mode: ausf
    app: free5gc-ausf
  ports:
    - name: http-free5gc-ausf-8000
      protocol: TCP
      port: 8000
      targetPort: 8000
