apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oai-my5grantester
  namespace: oai-cn5g
  labels:
    app: my5grantester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my5grantester
  template:
    metadata:
      labels:
        app: my5grantester
    spec:
      nodeSelector:
        nodetype: server
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: whitesnake
      containers:
        - name: oai-my5grantester
          image: carlosmenin/my5grantester:latest
          #command: ["sleep", "infinity"]
          env:
            - name: NGAP_LOCAL_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NGAP_REMOTE_ADDR
              value: oai-amf
            - name: GTPU_LOCAL_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MCC
              value: "208"
            - name: MNC
              value: "95"
            - name: TAC
              value: 00a000
            - name: GNBID
              value: "000003"
            - name: SST_GNB
              value: de
            - name: SST_UE
              value: "222"
            - name: SD
              value: "00007b"
            - name: MSIN
              value: "0000000031"
            - name: OPC
              value: C42449363BBAD02B66D16BC975D77CC1
            - name: KEY
              value: fec86ba6eb707ed08905757b1bb44b8f
            - name: AMF
              value: "8000"
            - name: SQN
              value: "000000000020"
            - name: DNN
              value: default
            - name: TEST
              value: parallel
            - name: NUM_UE
              value: "1"
            - name: DELAY
              value: "1000"
            - name: TIME
              value: "20"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oai-my5grantester
  namespace: cemenin
  labels:
    epc-mode: my5grantester
spec:
  selector:
    matchLabels:
      epc-mode: my5grantester
  endpoints:
    - interval: 30s
      port: oai-my5grantester-tcp-9100
---
apiVersion: v1
kind: Service
metadata:
  name:  oai-my5grantester
  namespace: oai-cn5g
  labels:
    epc-mode: my5grantester
spec:
  selector:
    epc-mode: my5grantester
  ports:
    - name: oai-my5grantester-tcp-80
      protocol: TCP
      port: 80
    - name: oai-my5grantester-tcp-3000
      protocol: TCP
      port: 3000
    - name: oai-my5grantester-tcp-9100
      protocol: TCP
      port: 9100
      targetPort: 9100
---