apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: free5gc-tcpdump-pv-claim
  namespace: free5gc
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi