apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open5gs-tcpdump-pv-claim
  namespace: cemenin
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi