apiVersion: v1
kind: Service
metadata:
  name: iperf
  namespace: free5gc
  labels:
    epc-mode: iperf
    promotheus: free5gc-monitor
spec:
  selector:
    epc-mode: iperf
  ports:
    - name: f5g-iperf-5001
      protocol: TCP
      port: 5001
      targetPort: 5001
    - name: f5g-iperf-udp-5001
      protocol: UDP
      port: 5001
      targetPort: 5001
    - name: f5g-iperf-9100
      protocol: TCP
      port: 9100
      targetPort: 9100
---    
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: free5gc-iperf
  namespace: free5gc
  labels:
    epc-mode: pcf
    promotheus: free5gc-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: iperf
  template:
    metadata:   
      labels:
        epc-mode: iperf
    spec:  
      nodeSelector:
        kubernetes.io/arch: amd64
        #kubernetes.io/hostname: whitesnake
      containers: 

        - name: iperf
          image: mlabbe/iperf:latest  
          ports:
            - containerPort: 5001
              name: f5g-iperf-5001
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]  
          #command: ["/bin/iperf", "-s", "--histograms"]
          command: ["iperf","-s","-p","5001"]