apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  namespace: cemenin
  labels:
    epc-mode: smf
data:
  smf.yaml: |
    logger:
        file: /var/log/open5gs/smf.log

    sbi:
      server:
        no_tls: true
      client:
        no_tls: true

    smf:
      sbi:
        - dev: eth0
          port: 80
          advertise: open5gs-smf
      metrics:
        addr: 0.0.0.0
        port: 9090
      pfcp:
        - dev: eth0
      gtpc:
        - dev: eth0
      gtpu:
        - dev: eth0
      subnet:
        - addr: 192.168.0.1/16
          dnn: internet
        - addr: 10.41.0.1/16
          dnn: slice01
      dns:
        - 10.96.0.10
      mtu: 1400
      ctf:
        enabled: auto
      freeDiameter: /etc/freeDiameter/smf.conf
      info:
        - s_nssai:
          - sst: 1
            dnn:
              - internet
          - sst: 1
            sd: 000001
            dnn:
              - slice01

        
    nrf:
      sbi:
        - name: open5gs-nrf
    

    upf:
      pfcp:
        # - addr: open5gs-upf
        #   dnn: [internet]
        - addr: open5gs-upf-1
          dnn: [internet, slice01]

    metrics:
        addr: 0.0.0.0
        port: 9090

    time:
      nf_instance:
        heartbeat: 20
      message:
        duration: 3000
      handover:
        duration: 500
